import { useEffect, useState } from 'react'
import robotLogo from './assets/sentinel-robot-logo.svg'

const stages = [
  ['01', 'Sense', 'Stream telemetry from every robot, mission, and resource.'],
  ['02', 'Predict', 'Surface failure risk before it becomes a mission event.'],
  ['03', 'Understand', 'Trace dependencies across tasks, missions, and fleet capacity.'],
  ['04', 'Decide', 'Score recovery candidates against health, load, distance, and energy.'],
  ['05', 'Recover', 'Migrate critical work and preserve mission continuity.'],
  ['06', 'Rebalance', 'Spread load while protecting reserve capacity.'],
  ['07', 'Verify', 'Prove recovery with an auditable operational timeline.'],
]

export default function Landing({ robots, risk, navigate, signIn, startDemo, user }) {
  const [selectedStage, setSelectedStage] = useState(0)
  const [scrolling, setScrolling] = useState(false)
  const active = robots.filter((robot) => robot.state === 'Healthy' || robot.state === 'Warning').length
  useEffect(() => { const onScroll = () => setScrolling(window.scrollY > 18); window.addEventListener('scroll', onScroll); return () => window.removeEventListener('scroll', onScroll) }, [])
  return <div className="landing-page">
    <header className={scrolling ? 'public-nav compact' : 'public-nav'}><button className="public-brand" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}><span className="public-mark">S</span><span><strong>SENTINEL ROBOTICS</strong><small>FLEET RECOVERY AI</small></span></button><nav className="public-links"><a href="#platform">Platform</a><a href="#method">Technology</a><a href="#recovery">Recovery</a><a href="#analytics">Analytics</a><a href="#footer">Resources</a><a href="/developers" onClick={(event) => { event.preventDefault(); navigate('/developers') }}>Developers</a></nav><div className="public-actions">{user ? <button className="public-user" onClick={() => navigate('/profile')}>{user.photoURL && <img src={user.photoURL} alt="" />}{user.name} <span>⌄</span></button> : <button className="public-signin" onClick={() => navigate('/login')}>Sign in</button>}<button className="public-live" onClick={() => navigate(user ? '/simulation' : '/login')}>Live operations <span>↗</span></button></div></header>
    <main>
      <section className="public-hero"><div className="hero-copy"><span className="public-kicker">HACKFUSION 2026 · THEME 04</span><h1>Autonomous fleet recovery,<br /><em>powered by AI.</em></h1><p>Sentinel Fleet Recovery AI predicts robot failures, contains cascading failures, dynamically reallocates missions, and restores fleet performance in real time.</p><div className="hero-actions"><button className="hero-primary" onClick={() => navigate('/simulation')}>Explore platform <span>↗</span></button><button className="hero-secondary" onClick={startDemo}>Launch live simulation <span>▶</span></button></div><button className="hero-link" onClick={() => document.querySelector('#recovery')?.scrollIntoView({ behavior: 'smooth' })}>View recovery demo <span>↓</span></button></div><HeroNetwork robots={robots} risk={risk} /></section>
      <section className="proof-strip"><div><strong>{robots.length || 25}</strong><span>robots monitored</span></div><div><strong>{active}</strong><span>operational now</span></div><div><strong>98.4%</strong><span>mission performance</span></div><div><strong>24/7</strong><span>fleet intelligence</span></div><small>SIMULATION ENVIRONMENT · DETERMINISTIC SEED 2026</small></section>
      <section className="editorial-section problem-section" id="platform"><div className="section-label">01 / THE PROBLEM</div><div className="split-story"><h2>When one robot fails,<br /><em>the mission doesn't have to.</em></h2><div><p>Cascading failures turn isolated anomalies into mission-level risk. Sentinel keeps the chain visible, scores every decision, and protects the work that matters most.</p><button className="arrow-link" onClick={() => navigate('/failure-analysis')}>Understand the cascade <span>→</span></button></div></div><div className="cascade-rail"><CascadeItem number="01" title="Robot failure" /><CascadeItem number="02" title="Signal degradation" /><CascadeItem number="03" title="Task disruption" /><CascadeItem number="04" title="Mission risk" /><CascadeItem number="05" title="Fleet overload" /></div></section>
      <section className="method-section" id="method"><div className="method-intro"><div className="section-label">02 / THE INTELLIGENCE LOOP</div><h2>From signal to<br /><em>certainty.</em></h2><p>One recovery loop connects telemetry, prediction, explainability, and action into an auditable operating model.</p></div><div className="method-steps">{stages.map(([number, title, description], index) => <button key={title} className={selectedStage === index ? 'method-step selected' : 'method-step'} onClick={() => setSelectedStage(index)}><span>{number}</span><div><strong>{title}</strong><small>{description}</small></div><b>↗</b></button>)}</div></section>
      <section className="fleet-story" id="fleet"><div className="section-label">03 / LIVE FLEET INTELLIGENCE</div><div className="fleet-heading"><h2>One intelligent view<br />of the entire <em>fleet.</em></h2><p>Click through to the operations control room for robot-level telemetry, digital twins, failure analysis, and recovery orchestration.</p></div><div className="fleet-preview"><div className="fleet-preview-map"><div className="preview-grid" />{robots.slice(0, 42).map((robot) => <button key={robot.id} className={`preview-robot ${robot.state.toLowerCase()}`} style={{ left: `${robot.x}%`, top: `${robot.y}%` }} onClick={() => navigate('/fleet')} aria-label={`Open ${robot.id}`}><i /></button>)}<span className="preview-label north">NORTH DOCK</span><span className="preview-label east">EAST GRID</span><div className="preview-float-card"><span className="tiny-status critical" />R-004 <strong>93% risk</strong><small>Motor anomaly detected</small></div></div><div className="fleet-preview-copy"><span className="public-kicker">DIGITAL TWIN / R-004</span><h3>Predict the failure<br />before it <em>propagates.</em></h3><div className="twin-stats"><span><b>93%</b><small>failure risk</small></span><span><b>94%</b><small>confidence</small></span><span><b>08m</b><small>estimated time</small></span></div><button className="arrow-link" onClick={() => navigate('/fleet')}>Open fleet intelligence <span>→</span></button></div></div></section>
      <section className="recovery-story" id="recovery"><div className="recovery-copy"><div className="section-label">04 / HOW SENTINEL RECOVERS A FLEET</div><h2>Recovery is not a reaction.<br /><em>It's an intelligence loop.</em></h2><p>Run the existing eight-phase simulation and watch the fleet move from anomaly to verified recovery.</p><button className="hero-primary" onClick={() => navigate(user ? '/simulation' : '/login')}>Try the live recovery simulation <span>↗</span></button></div><div className="recovery-phases">{['Predict', 'Analyze', 'Prioritize', 'Migrate', 'Rebalance', 'Recover'].map((phase, index) => <div key={phase} className={index === 0 ? 'recovery-phase active' : 'recovery-phase'}><span>0{index + 1}</span><strong>{phase}</strong><i /></div>)}</div></section>
      <section className="closing-section" id="analytics"><div className="section-label">05 / BUILT FOR THE REAL WORLD</div><h2>Resilience is a<br /><em>fleet capability.</em></h2><p>Sentinel turns failure propagation into a measurable, explainable, and recoverable operating state.</p><div className="closing-links"><button onClick={() => navigate('/analytics')}>Explore analytics <span>↗</span></button><button onClick={() => navigate('/recovery')}>Open recovery center <span>↗</span></button><button onClick={() => navigate('/simulation')}>Launch simulation <span>↗</span></button></div></section>
    </main><footer className="public-footer" id="footer"><div><button className="public-brand"><span className="public-mark">S</span><span><strong>SENTINEL ROBOTICS</strong><small>FLEET RECOVERY AI</small></span></button><p>Autonomous intelligence for resilient robot fleets.</p></div><div><small>PLATFORM</small><button onClick={() => navigate('/simulation')}>Simulation</button><button onClick={() => navigate('/fleet')}>Fleet intelligence</button><button onClick={() => navigate('/recovery')}>Recovery center</button></div><div><small>SYSTEM</small><button onClick={() => navigate('/analytics')}>Analytics</button><button onClick={() => navigate('/events')}>Event intelligence</button><button onClick={() => navigate('/login')}>Sign in</button></div><div className="footer-end">© 2026 Sentinel Robotics<br /><span>Simulation environment</span></div></footer>
  </div>
}

export function RecoveryLanding({ robots, risk, navigate, startDemo, user }) {
  return <div className="landing-page recovery-public-page">
    <header className="public-nav"><button className="public-brand" onClick={() => navigate('/')}><span className="public-mark">S</span><span><strong>SENTINEL ROBOTICS</strong><small>FLEET RECOVERY AI</small></span></button><nav className="public-links"><a href="/#platform">Platform</a><a href="/#method">Technology</a><a href="/recovery">Recovery</a><a href="/#analytics">Analytics</a><a href="/#footer">Resources</a><a href="/developers">Developers</a></nav><div className="public-actions">{user ? <button className="public-user" onClick={() => navigate('/profile')}>{user.photoURL && <img src={user.photoURL} alt="" />}{user.name} <span>⌄</span></button> : <button className="public-signin" onClick={() => navigate('/login')}>Sign in</button>}<button className="public-live" onClick={() => navigate('/simulation')}>Live operations <span>↗</span></button></div></header>
    <main>
      <section className="public-hero recovery-public-hero"><div className="hero-copy"><span className="public-kicker">04 / RECOVERY CENTER · THEME 04</span><h1>Recovery that keeps<br /><em>missions moving.</em></h1><p>When failures propagate, Sentinel scores every recovery path, migrates critical work, and brings the fleet back to a stable operating state.</p><div className="hero-actions"><button className="hero-primary" onClick={startDemo}>Start recovery simulation <span>▶</span></button><button className="hero-secondary" onClick={() => navigate('/simulation')}>Open live operations <span>↗</span></button></div><button className="hero-link" onClick={() => document.querySelector('#recovery-method')?.scrollIntoView({ behavior: 'smooth' })}>See the recovery loop <span>↓</span></button></div><HeroNetwork robots={robots} risk={risk} /></section>
      <section className="proof-strip"><div><strong>08</strong><span>recovery phases</span></div><div><strong>89.7%</strong><span>performance recovered</span></div><div><strong>100%</strong><span>critical work protected</span></div><div><strong>91.8%</strong><span>recovery success</span></div><small>DETERMINISTIC SIMULATION · AUDITABLE DECISIONS</small></section>
      <section className="editorial-section" id="recovery-method"><div className="section-label">01 / THE RECOVERY LOOP</div><div className="split-story"><h2>Contain the cascade,<br /><em>preserve the mission.</em></h2><div><p>Recovery is a sequence of explainable decisions. Sentinel finds the failure boundary, ranks replacement capacity, migrates tasks, and verifies that mission performance has returned.</p><button className="arrow-link" onClick={() => navigate('/failure-analysis')}>Explore failure analysis <span>→</span></button></div></div><div className="cascade-rail recovery-rail"><CascadeItem number="01" title="Detect" /><CascadeItem number="02" title="Predict" /><CascadeItem number="03" title="Migrate" /><CascadeItem number="04" title="Rebalance" /><CascadeItem number="05" title="Verify" /></div></section>
      <section className="recovery-story recovery-public-band"><div className="recovery-copy"><div className="section-label">02 / MISSION CONTINUITY</div><h2>Every decision has<br /><em>a measurable outcome.</em></h2><p>See which robots are affected, which missions are protected, and how much capacity remains before you commit to a recovery action.</p><button className="hero-primary" onClick={() => navigate('/simulation')}>Open recovery center <span>↗</span></button></div><div className="recovery-phases">{['Failure boundary mapped', 'Replacement scored', 'Critical tasks migrated', 'Fleet capacity rebalanced', 'Recovery verified'].map((phase, index) => <div className={index === 0 ? 'recovery-phase active' : 'recovery-phase'} key={phase}><span>0{index + 1}</span><strong>{phase}</strong><i /></div>)}</div></section>
      <section className="closing-section"><div className="section-label">03 / READY WHEN FAILURE ISN'T</div><h2>Make resilience a<br /><em>fleet capability.</em></h2><p>Move from anomaly to verified recovery with one intelligent operating layer.</p><div className="closing-links"><button onClick={startDemo}>Run simulation <span>↗</span></button><button onClick={() => navigate('/simulation')}>Launch simulation <span>↗</span></button></div></section>
    </main><footer className="public-footer" id="footer"><div><button className="public-brand" onClick={() => navigate('/')}><span className="public-mark">S</span><span><strong>SENTINEL ROBOTICS</strong><small>FLEET RECOVERY AI</small></span></button><p>Autonomous intelligence for resilient robot fleets.</p></div><div><small>PLATFORM</small><button onClick={() => navigate('/simulation')}>Simulation</button><button onClick={() => navigate('/fleet')}>Fleet intelligence</button></div><div><small>SYSTEM</small><button onClick={() => navigate('/analytics')}>Analytics</button><button onClick={() => navigate('/login')}>Sign in</button></div><div className="footer-end">© 2026 Sentinel Robotics<br /><span>Simulation environment</span></div></footer>
  </div>
}

export function DevelopersPage({ navigate }) {
  const members = [
    ['Member 01', 'Systems & Robotics'],
    ['Member 02', 'AI & Simulation'],
    ['Member 03', 'Product & Experience'],
    ['Member 04', 'Platform Engineering'],
  ]
  return <div className="landing-page developers-page">
    <header className="public-nav compact"><button className="public-brand" onClick={() => navigate('/')}><span className="public-mark">S</span><span><strong>SENTINEL ROBOTICS</strong><small>FLEET RECOVERY AI</small></span></button><nav className="public-links"><a href="/#platform">Platform</a><a href="/#method">Technology</a><a href="/recovery">Recovery</a><a href="/#analytics">Analytics</a><a href="/#footer">Resources</a><a href="/developers">Developers</a></nav><div className="public-actions"><button className="public-signin" onClick={() => navigate('/login')}>Sign in</button><button className="public-live" onClick={() => navigate('/simulation')}>Live operations <span>↗</span></button></div></header>
    <main className="developers-main"><span className="public-kicker">SENTINEL ROBOTICS · TEAM</span><h1>Meet the<br /><em>developers.</em></h1><p className="developers-intro">The people building resilient intelligence for autonomous fleets.</p><section className="developer-grid">{members.map(([name, role], index) => <article className="developer-card" key={name}><div className="developer-avatar">0{index + 1}</div><span className="section-label">TEAM MEMBER</span><h2>{name}</h2><p>{role}</p></article>)}</section><button className="arrow-link developers-back" onClick={() => navigate('/')}>Back to Sentinel Robotics <span>→</span></button></main><footer className="public-footer"><div><button className="public-brand" onClick={() => navigate('/')}><span className="public-mark">S</span><span><strong>SENTINEL ROBOTICS</strong><small>FLEET RECOVERY AI</small></span></button><p>Autonomous intelligence for resilient robot fleets.</p></div><div className="footer-end">© 2026 Sentinel Robotics<br /><span>Simulation environment</span></div></footer>
  </div>
}

function HeroNetwork({ robots, risk }) { return <div className="hero-network"><div className="network-grid" /><div className="network-orbit orbit-a" /><div className="network-orbit orbit-b" />{robots.slice(0, 60).map((robot) => <span key={robot.id} className={`hero-robot ${robot.state.toLowerCase()}`} style={{ left: `${robot.x}%`, top: `${robot.y}%`, animationDelay: `${(robot.x + robot.y) % 4}s` }} />)}<div className="hero-core"><span>AI</span><strong>RECOVERY<br />LAYER</strong><small>RISK {risk}%</small></div><div className="network-caption"><span className="pulse-dot" />LIVE SIMULATION <b>25 ROBOTS / 03 MISSIONS</b></div></div> }
function CascadeItem({ number, title }) { return <div className="cascade-item"><span>{number}</span><strong>{title}</strong><i>↓</i></div> }
